FROM python:3.10-slim-buster
RUN apt update
RUN apt-get install -qq -y jq curl wget sqlite3
RUN mkdir /app
WORKDIR /app
ADD generated_requirements.txt /app
RUN pip install --upgrade -r generated_requirements.txt # generated by release.sh
ADD entrypoint.sh /app
RUN chmod +x entrypoint.sh
# Next line will break docker layer caching, if any file is changed in the pwd.
ADD . /app
CMD ["./entrypoint.sh"]
