name: Docker Image CI

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:

env:
  IMAGE_NAME: spyplane

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to PTN Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Generate version timestamp
        id: prep
        run: |
          ts=$(date "+%Y%m%d-%H%M%S")
          echo "BUILD_VER=${ts}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.BUILD_VER }}
            ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
